try4:
	sudo -E python3 -m jupyter notebook --allow-root --ip="0.0.0.0" --NotebookApp.token='yaml' --port=80
try3:
	python3 -m jupyter notebook --allow-root --ip="0.0.0.0" --NotebookApp.token='yaml' --port=8080 
