apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: product-deployment
spec:
  selector:
    matchLabels:
      app: product-list
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: product-list
    spec:
      containers:
      - name: product-list
        image: tbutzer/product_server
        ports:
        - containerPort: 80

